BEGIN { 
    print "/* generated by getLMA.awk */" 
    lma_text = 0;
    lma_data = 0;
    lma_vect = 0;
}
/\.text/    { lma_text = $5; }
/\.data/    { lma_data = $5; }
/\.vectors/ { lma_vect = $5; }
END {  
    printf("const uint32_t text_lma = 0x%s;\n", lma_text);
    printf("const uint32_t data_lma = 0x%s;\n", lma_data);
    printf("const uint32_t vect_lma = 0x%s;\n", lma_vect);
    print "/* EOF */"
}